version: '3.8'

services:

  mysql:

    image: mysql:8.0
    container_name: ms-user-db
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: ms_user_ms
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: